### ISSUE TITLE
Use asynchronous functions

### ISSUE THREAD

**Issue by baldore** [siddharthkp/auto-install#10]
I think the performance can be improved if instead of using some sync functions you just use asynchronous methods. Let me know what do you think.

**Comment by siddharthkp** [comment]
Can! 

I started with asynchronous functions and ended up with multiple installations happening at once.

For the sake of clarity, I made everything sequential. 

Will start making things async now that things are working smoothly.

Although, the biggest performance bottleneck was not in the code but in installing modules from the registry :smile:

**Comment by himanshuchauhan** [comment]
Hi ,I would like to start working on this.Any pointers where I should begin.?
