### ISSUE TITLE
ES6 Modules

### ISSUE THREAD

**Issue by casoetan** [siddharthkp/auto-install#11]
This does not work when using ES6 module import synthax

``` js
import express from 'express'
```

**Comment by siddharthkp** [comment]
@casoetan I don't understand es6 modules completely yet, will get around to this soon-ish?

Meanwhile, A pull request is welcome :smile:

**Comment by olalonde** [comment]
Could be done by parsing with babel (or https://www.npmjs.com/package/detective-es6) and inspecting the AST for the `import from` node. 

Also, I noticed that every file is inspected each time a file changes instead of only inspecting the file that has changed, might want to fix that for better perf.

**Comment by siddharthkp** [comment]
@olalonde Yes, some optimizations are due. All files need to be parsed only when a file is deleted (to remove extra modules that are installed but not used).

**Comment by olalonde** [comment]
Ah I see, I didn't think about that. Could still be optimised by caching which files import which modules but a bit more complex.

**Comment by siddharthkp** [comment]
@olalonde Can, but not sure if the performance gain is worth the complexity.
I have also been toying with the idea of a temporary git setup to watch diff

**Comment by siddharthkp** [comment]
@casoetan @olalonde Any clue how to distinguish between a local module (from a file) and one from the npm registry?

**Comment by olalonde** [comment]
It should be the same as with `require()`.

`import something from 'some-module'`

compiles to

`var something = require('some-module')`

and

`import something from './some-module'`

compiles to

`var something = require('./some-module')`

etc. :)

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=import%20something%20from%20'some-module'

**Comment by siddharthkp** [comment]
Done in `1.6.0`! PR - https://github.com/siddharthkp/auto-install/pull/28
