### ISSUE TITLE
Reparse after first run

### ISSUE THREAD

**Issue by fregante** [siddharthkp/auto-install#29]
The first install might take a bit and if I already added another `require` it won't be installed until the next save. (minor issue though)

So it should probably:
1. parse & install
2. init watchers
3. parse & install

Or simply
1. init watchers
2. parse & install

**Comment by siddharthkp** [comment]
@bfred-it This will work beautifully when I move to a more async fashion, also pointed out in https://github.com/siddharthkp/auto-install/issues/10
