### ISSUE TITLE
Add an author whitelist for secure mode

### ISSUE THREAD

**Issue by KoryNunn** [siddharthkp/auto-install#30]
I use hundreds of modules that I wrote that don't have many stars.
It'd be really handy to also be able to allow automatic installation of my own modules via a white-list.

**Comment by siddharthkp** [comment]
@KoryNunn Added in https://github.com/siddharthkp/auto-install/pull/41

Usage: `auto-install --secure --trust-author KoryNunn`

Does not support multiple authors right now. According to me that would be cli parameters overkill. I am thinking of moving these `--flags` to `package.json`. What do you think?

Example:

``` json
"auto-install": {
    "secure": "true",
    "trusted-authors": ["KoryNunn", "siddharthkp"]
},
```

**Comment by KoryNunn** [comment]
Looks good.
