### ISSUE TITLE
[Question] Editor in README

### ISSUE THREAD

**Issue by AdrianVovk** [siddharthkp/auto-install#87]
What is the editor in the readme? I know this is a little off topic, but I'm just curious

**Comment by siddharthkp** [comment]
Wrote about it here:
https://github.com/siddharthkp/ama/issues/5

tl;dr: atom with 80s pastel theme

**Comment by AdrianVovk** [comment]
What are the arrows and the overflow menu? Also what is the ui theme?

I'm making an IDE based on atom and that looks super slick.
